name: cpeb4
dependencies:
  - python=3.8
  - jinja2
  - notebook
  - numpy
  - pandas
  - scipy
  - matplotlib
  - conda-forge::openmm==7.5.1
  - conda-forge::mdtraj
  - pip
  - pip:
    - mdanalysis
    - ovito
